# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'url'
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/checkout@v2
    - name: download
      uses: jomiller891/download-action@main
      env:
        GITHUB_TOKEN: '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'
      with:
        url: ${{ inputs.url }}
        actor: ${{ github.actor }}
        repo: ${{ github.repository }}
